name:                SATbench
version:             0.1.2.0
license:             BSD3
author:              "Shuji Narazaki"
maintainer:          "shuji.narazaki@gmail.com"
copyright:           "2018 Shuji Narazaki"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Logic

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- text >=1.2

library:
  source-dirs: src

executables:
  sat-benchmark:
    main:                sat-benchmark.hs
    source-dirs:         .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7
      - unix >=2.7
      - process >=1.2
  gsink:
    main:                gsink.hs
    source-dirs:         .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7
      - unix >=2.7
      - process >=1.2
      - parsec
