[package]
name = "sat_bench"
version = "0.3.0"
authors = ["Shuji Narazaki <shujinarazaki@protonmail.com>"]
edition = "2018"

[dependencies]
chrono ="^0.4"
lazy_static = "^1.3"
regex = "^1.1"
structopt = "^0.2"
