[package]
name = "sat-bench"
version = "0.6.5"
authors = ["Shuji Narazaki <shujinarazaki@protonmail.com>"]
edition = "2018"

[dependencies]
chrono ="^0.4"
crossbeam = "0.7"
discord-rpc-client = "0.3"
http = "0.1"
lazy_static = "^1.4"
regex = "^1.3"
reqwest = "0.9"
serde_json = "1.0"
serenity = {version = "^0.7", default-features = false, features = [ "builder", "cache", "client", "framework", "model", "standard_framework", "rustls_backend" ]}
structopt = "^0.3"
